name: 'actions/install'
description: 'Install all dependencies'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: installing node dependencies
      if: hashFiles('package.json') != ''
      run: npm install --force --verbose
      shell: bash

    - name: installing python dependencies
      if: hashFiles('pyproject.toml') != ''
      run: |
        pip install .[dev]
        export PATH=$PATH:/app/.local/bin
        poetry export --without-hashes --output requirements.txt
      shell: bash

    - uses: yadickson/actions-steps/cache-dependencies@v1
